# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-25 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MS_MarketAccess',
            new_name='EC_MarketAccess',
        ),
        migrations.RenameModel(
            old_name='MS_MarketSales',
            new_name='EC_MarketSales',
        ),
        migrations.RenameModel(
            old_name='MS_MarketSalesDetails',
            new_name='EC_MarketSalesDetails',
        ),
    ]
