# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-26 01:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore_ecommerce', '0002_auto_20180225_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EC_MarketSales',
            new_name='EC_ShoppingCart',
        ),
        migrations.RenameModel(
            old_name='EC_MarketSalesDetails',
            new_name='EC_ShoppingCartItems',
        ),
    ]
