# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-26 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore_ecommerce', '0003_auto_20180226_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ec_shoppingcartitems',
            old_name='receipt',
            new_name='cart',
        ),
    ]
