# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-26 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore_ecommerce', '0004_auto_20180226_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec_shoppingcart',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=18),
        ),
        migrations.AlterField(
            model_name='ec_shoppingcartitems',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='ec_shoppingcartitems',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
