# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-01 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore_managment', '0030_auto_20180226_0521'),
        ('xlstore_ecommerce', '0005_auto_20180226_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='EC_CompanyMobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EC_CompanySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_ecommerce', models.BooleanField(default=False)),
                ('paypal', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore_managment.MS_CompanyAdministrator')),
            ],
        ),
        migrations.AddField(
            model_name='ec_companymobile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore_ecommerce.EC_CompanySettings'),
        ),
    ]
