# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-01 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore_ecommerce', '0007_auto_20180301_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec_shoppingcart',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ec_shoppingcart',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
