# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-02 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore_ecommerce', '0008_auto_20180301_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec_companysettings',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xlstore_managment.MS_CompanyAdministrator'),
        ),
    ]
