# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-02 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore_ecommerce', '0009_auto_20180302_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec_companysettings',
            name='use_paypal',
            field=models.BooleanField(default=False),
        ),
    ]
