# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-03 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore_ecommerce', '0010_ec_companysettings_use_paypal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ec_companymobile',
            name='company',
        ),
        migrations.DeleteModel(
            name='EC_CompanyMobile',
        ),
    ]
