# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-03 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore_ecommerce', '0011_auto_20180303_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec_shoppingcart',
            name='finished_date',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
