# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 05:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import xlstore.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateTimeField(auto_created=True, default=datetime.datetime.now)),
                ('video', models.FileField(upload_to='advertisments/%Y/%m/%d/')),
                ('advertisment_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name_dotted', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=xlstore.models.get_company_profile_img)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=xlstore.models.get_company_cover_img)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('town', models.CharField(max_length=250, null=True)),
                ('address', models.TextField(null=True)),
                ('motto', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateTimeField(auto_created=True)),
                ('notification_id', models.IntegerField()),
                ('about', models.CharField(max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.Company')),
            ],
        ),
        migrations.CreateModel(
            name='MS_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_entry_stock', models.DateTimeField(auto_created=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('stock', models.IntegerField()),
                ('product_code', models.CharField(max_length=255)),
                ('place_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_date', models.DateTimeField(auto_created=True, default=datetime.datetime.now)),
                ('mention', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PostReplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_date', models.DateTimeField(auto_created=True, default=datetime.datetime.now)),
                ('reply_type', models.TextField(default='user')),
                ('reply_image', models.ImageField(blank=True, null=True, upload_to='posts_reply/%Y/%m/%d/')),
                ('reply_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateTimeField(auto_created=True, default=datetime.datetime.now)),
                ('poster_type', models.CharField(default='user', max_length=30)),
                ('post_text', models.TextField()),
                ('post_file', models.FileField(blank=True, null=True, upload_to='posts/%Y/%m/%d/')),
                ('file_type', models.CharField(blank=True, max_length=200, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xlstore.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_created=True, default=datetime.datetime.now)),
                ('commenter', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('commenter_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xlstore.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInteress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interess_date', models.DateTimeField(auto_created=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_date', models.DateTimeField(auto_created=True, default=datetime.datetime.now)),
                ('mention', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_date', models.DateTimeField(auto_created=True, default=datetime.datetime.now)),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateTimeField(auto_created=True, default=datetime.datetime.now)),
                ('product_name', models.CharField(max_length=250)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.TextField()),
                ('product_description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_to_be_posted', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('started_date', models.DateTimeField(auto_created=True)),
                ('status', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.Products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTradeMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_created=True)),
                ('sender', models.CharField(max_length=50)),
                ('receiver', models.CharField(max_length=50)),
                ('text_message', models.TextField(blank=True, null=True)),
                ('image_message', models.ImageField(blank=True, null=True, upload_to='trades/%Y/%m/%d/')),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted_by', models.CharField(default='none', max_length=40)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.ProductTrade')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, null=True)),
                ('user_name', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=xlstore.models.get_user_profile_img)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=xlstore.models.get_user_cover_img)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('town', models.TextField(null=True)),
                ('phone_number', models.TextField(null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('show_secret_details', models.BooleanField(default=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_date', models.DateTimeField(auto_created=True)),
                ('follower_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_user', to='xlstore.User')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_user', to='xlstore.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateTimeField(auto_created=True)),
                ('notification_maker', models.CharField(default='user', max_length=100)),
                ('notification_id', models.IntegerField()),
                ('about', models.CharField(max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xlstore.Company')),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to='xlstore.User')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xlstore.User')),
            ],
        ),
        migrations.AddField(
            model_name='producttrade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.User'),
        ),
        migrations.AddField(
            model_name='productpictures',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.Products'),
        ),
        migrations.AddField(
            model_name='productmention',
            name='mentioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.User'),
        ),
        migrations.AddField(
            model_name='productmention',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.Products'),
        ),
        migrations.AddField(
            model_name='productinteress',
            name='interesser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.User'),
        ),
        migrations.AddField(
            model_name='productinteress',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.Products'),
        ),
        migrations.AddField(
            model_name='productcomments',
            name='commenter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xlstore.User'),
        ),
        migrations.AddField(
            model_name='productcomments',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.Products'),
        ),
        migrations.AddField(
            model_name='posts',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xlstore.User'),
        ),
        migrations.AddField(
            model_name='postreplies',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.Posts'),
        ),
        migrations.AddField(
            model_name='postreplies',
            name='replyer_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xlstore.Company'),
        ),
        migrations.AddField(
            model_name='postreplies',
            name='replyer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xlstore.User'),
        ),
        migrations.AddField(
            model_name='postmention',
            name='mentioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.User'),
        ),
        migrations.AddField(
            model_name='postmention',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.Posts'),
        ),
        migrations.AddField(
            model_name='ms_products',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.Products'),
        ),
        migrations.AddField(
            model_name='followers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.User'),
        ),
        migrations.AddField(
            model_name='companynotifications',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xlstore.User'),
        ),
        migrations.AddField(
            model_name='categories',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.Company'),
        ),
        migrations.AddField(
            model_name='advertisments',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.Company'),
        ),
        migrations.AddField(
            model_name='advertisments',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.Products'),
        ),
		migrations.CreateModel(
            name='TradeAgreements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_date', models.DateField(auto_created=True, blank=True, null=True)),
                ('agreement_date', models.DateField(auto_created=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('is_finished', models.BooleanField(default=False)),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xlstore.ProductTrade')),
            ],
        ),
        migrations.AddField(
            model_name='producttrademessages',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producttrademessages',
            name='latitude',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='producttrademessages',
            name='longitude',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
