# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ms_products',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xlstore.Products'),
        ),
    ]
