# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0005_auto_20180116_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycategories',
            name='image',
            field=models.ImageField(default='', upload_to='admin/categories/'),
            preserve_default=False,
        ),
    ]
