# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0006_companycategories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_seen_tutorial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_seen_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
