# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0008_auto_20180211_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmention',
            old_name='mentioner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='postreplies',
            old_name='replyer_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='postreplies',
            old_name='replyer_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='poster',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='productcomments',
            old_name='commenter_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='productcomments',
            old_name='commenter_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='productinteress',
            old_name='interesser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='productmention',
            old_name='mentioner',
            new_name='user',
        ),
    ]
