# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xlstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MS_CompanyAdministrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_created=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/%Y/%m/%d/')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xlstore.Company')),
            ],
        ),
        migrations.CreateModel(
            name='MS_LicenceKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expary_date', models.DateTimeField(auto_created=True)),
                ('activated_date', models.DateTimeField(auto_created=True)),
                ('licence_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='desactivated', max_length=120)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xlstore_managment.MS_CompanyAdministrator')),
            ],
        ),
        migrations.CreateModel(
            name='MS_ProductEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_created=True)),
                ('quantity_before', models.IntegerField()),
                ('quantity_added', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.MS_Products')),
            ],
        ),
        migrations.CreateModel(
            name='MS_ReceiptDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_date', models.DateTimeField(auto_created=True)),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('is_discounted', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default='0')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.MS_Products')),
            ],
        ),
        migrations.CreateModel(
            name='MS_Receipts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_date', models.DateTimeField(auto_created=True)),
                ('saved_date_timezone', models.DateTimeField(auto_created=True)),
                ('receipt_number', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='created', max_length=50)),
                ('other_charges', models.IntegerField(default='0')),
                ('discount', models.IntegerField(default='0')),
                ('total_paid', models.IntegerField(default='0')),
                ('total_net', models.IntegerField(default='0')),
                ('paid_by', models.CharField(default='cash', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore_managment.MS_CompanyAdministrator')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xlstore.User')),
            ],
        ),
        migrations.AddField(
            model_name='ms_receiptdetails',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore_managment.MS_Receipts'),
        ),
    ]
