# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore_managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ms_receipts',
            name='saved_date',
            field=models.DateField(auto_created=True),
        ),
    ]
