# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore_managment', '0003_ms_productentry_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ms_receiptdetails',
            name='item_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
