# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #('xlstore', '0002_tradeagreement'),
        ('xlstore_managment', '0005_auto_20170808_1632'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='ms_receiptdetails',
        #    name='trade',
        #    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xlstore.ProductTrade'),
        #),
    ]
