# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore_managment', '0006_auto_20170823_1632'),
    ]

    operations = [
	
    ]
