# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0002_auto_20170914_1957'),
        ('xlstore_managment', '0007_auto_20170914_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='MS_MarketAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_date', models.DateField(auto_created=True)),
                ('time_to', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('time_from', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('access_time', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore_managment.MS_CompanyAdministrator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.User')),
            ],
        ),
        migrations.CreateModel(
            name='MS_Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reduce_after_trade_agreed', models.BooleanField(default=False)),
                ('allow_user_to_succeed', models.BooleanField(default=False)),
                ('print_bill', models.BooleanField(default=False)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('internationalize', models.BooleanField(default=False)),
                ('access_market', models.BooleanField(default=False)),
                ('time_market_access', models.IntegerField(default='30')),
                ('always_admin', models.BooleanField(default=False)),
                ('comment_product', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xlstore_managment.MS_CompanyAdministrator')),
            ],
        ),
    ]
