# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0002_auto_20170914_1957'),
        ('xlstore_managment', '0008_auto_20171006_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='ms_settings',
            name='is_currency_changed',
            field=models.BooleanField(default=False),
        ),
    ]
