# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0002_auto_20170914_1957'),
        ('xlstore_managment', '0009_auto_20171009_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ms_licencekey',
            name='activated_date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='ms_licencekey',
            name='expary_date',
            field=models.DateField(auto_created=True),
        ),
    ]
