# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0002_auto_20170914_1957'),
        ('xlstore_managment', '0010_auto_20171010_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='MS_LicenceKeyActivations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expary_date', models.DateField(auto_created=True)),
                ('activated_date', models.DateField(auto_created=True)),
                ('money', models.IntegerField(default='0')),
                ('currency', models.CharField(default='USD', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore_managment.MS_LicenceKey')),
            ],
        ),
    ]
