# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-15 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0002_auto_20170914_1957'),
        ('xlstore_managment', '0011_auto_20171012_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ms_licencekeyactivations',
            old_name='money',
            new_name='ammount',
        ),
    ]
