# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0002_auto_20170914_1957'),
        ('xlstore_managment', '0012_auto_20171015_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='ms_licencekey',
            name='ammount',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='ms_licencekey',
            name='currency',
            field=models.CharField(default='USD', max_length=50),
        ),
    ]
