# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0003_companycategories'),
        ('xlstore_managment', '0013_auto_20171028_0710'),
    ]

    operations = [
       
    ]
