# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0004_auto_20171109_0744'),
        ('xlstore_managment', '0014_auto_20171109_0723'),
    ]

    operations = [
		
    ]
