# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-16 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0005_auto_20180116_1420'),
        ('xlstore_managment', '0015_auto_20171109_0744'),
    ]

    operations = [
        
    ]
