# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0006_companycategories_image'),
        ('xlstore_managment', '0016_auto_20180116_1420'),
    ]

    operations = [    
    ]
