# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0007_auto_20180120_0442'),
        ('xlstore_managment', '0017_auto_20180120_0432'),
    ]

    operations = [
        
    ]
