# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0007_auto_20180120_0442'),
        ('xlstore_managment', '0018_auto_20180120_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='MS_CompanyTeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_created=True)),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore_managment.MS_CompanyAdministrator')),
            ],
        ),
        migrations.AddField(
            model_name='ms_receipts',
            name='teller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xlstore_managment.MS_CompanyTeller'),
        ),
    ]
