# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0007_auto_20180120_0442'),
        ('xlstore_managment', '0019_auto_20180122_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='ms_companyteller',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
