# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import xlstore_managment.models


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0007_auto_20180120_0442'),
        ('xlstore_managment', '0020_auto_20180122_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='ms_companyteller',
            name='teller_image',
            field=models.ImageField(blank=True, null=True, upload_to=xlstore_managment.models.get_teller_img),
        ),
    ]
