# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-24 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0008_auto_20180211_1743'),
        ('xlstore_managment', '0023_auto_20180220_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='MS_MarketSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_date', models.DateTimeField(auto_created=True)),
                ('status', models.CharField(max_length=100)),
                ('total_paid', models.IntegerField(default='0')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore_managment.MS_MarketAccess')),
            ],
        ),
        migrations.CreateModel(
            name='MS_MarketSalesDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_date', models.DateTimeField(auto_created=True)),
                ('quantity', models.IntegerField()),
                ('item_price', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore.MS_Products')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xlstore_managment.MS_MarketSales')),
            ],
        ),
    ]
