# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-25 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0008_auto_20180211_1743'),
        ('xlstore_managment', '0024_auto_20180224_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ms_marketaccess',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ms_marketaccess',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ms_marketsales',
            name='market',
        ),
        migrations.RemoveField(
            model_name='ms_marketsalesdetails',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ms_marketsalesdetails',
            name='receipt',
        ),
        migrations.DeleteModel(
            name='MS_MarketAccess',
        ),
        migrations.DeleteModel(
            name='MS_MarketSales',
        ),
        migrations.DeleteModel(
            name='MS_MarketSalesDetails',
        ),
    ]
