# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-26 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0008_auto_20180211_1743'),
        ('xlstore_managment', '0027_auto_20180225_1629'),
    ]

    operations = [
        
    ]
