# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-26 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0008_auto_20180211_1743'),
        ('xlstore_managment', '0029_auto_20180226_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ms_productentry',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='ms_receiptdetails',
            name='discount',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=18),
        ),
        migrations.AlterField(
            model_name='ms_receiptdetails',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='ms_receipts',
            name='discount',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=18),
        ),
        migrations.AlterField(
            model_name='ms_receipts',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=18),
        ),
        migrations.AlterField(
            model_name='ms_receipts',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=18),
        ),
        migrations.AlterField(
            model_name='ms_receipts',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=18),
        ),
    ]
