# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-03 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0008_auto_20180211_1743'),
        ('xlstore_managment', '0036_auto_20180303_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='ms_companymobile',
            name='airline',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
