# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlstore', '0009_auto_20180319_0846'),
        ('xlstore_managment', '0038_auto_20180303_1705'),
    ]

    operations = [
        
    ]
